version: "3.9"

services:
  app:
    image: 192.168.50.11:5000/simulaiz:latest
    environment:
      - APP_ENV=${APP_ENV:-production}
      - SIMULAIZ_LOG_LEVEL=${SIMULAIZ_LOG_LEVEL:-INFO}
      - SIMULAIZ_PORT=${SIMULAIZ_PORT:-8000}
      - SKIP_DEFAULT_AVATAR_GENERATION=true
    volumes:
      # Mount CephFS for model storage to avoid filling local disk
      - type: bind
        source: /mnt/cephfs/storage/simulaiz/models
        target: /models
      - type: bind
        source: /mnt/cephfs/cache/huggingface
        target: /root/.cache/huggingface
      - type: bind
        source: /mnt/cephfs/storage/simulaiz/assets
        target: /app/assets
    networks:
      - webhost-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.simulaiz.rule=Host(`simulaiz.shared.neutralaiz.com`)"
        - "traefik.http.routers.simulaiz.entrypoints=web"
        - "traefik.http.services.simulaiz.loadbalancer.server.port=8000"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.path=/api/health"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.interval=10s"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.timeout=5s"
        - "traefik.http.routers.simulaiz.middlewares=simulaiz-headers"
        - "traefik.http.middlewares.simulaiz-headers.headers.stsSeconds=31536000"
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G

networks:
  webhost-network:
    external: true
