version: "3.9"

services:
  app:
    image: simulaz/app:latest
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV:-production}
      - SIMULAIZ_LOG_LEVEL=${SIMULAIZ_LOG_LEVEL:-INFO}
      - SIMULAIZ_PORT=${SIMULAIZ_PORT:-8000}
    networks:
      - webhost-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.simulaiz.rule=Host(`simulaiz.test.neutralaiz.com`)"
        - "traefik.http.routers.simulaiz.entrypoints=web"
        - "traefik.http.services.simulaiz.loadbalancer.server.port=8000"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.interval=10s"
        - "traefik.http.services.simulaiz.loadbalancer.healthcheck.timeout=5s"
        - "traefik.http.routers.simulaiz.middlewares=simulaiz-headers"
        - "traefik.http.middlewares.simulaiz-headers.headers.stsSeconds=31536000"
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
          generic_resources:
            - discrete_resource_spec:
                kind: 'gpu'
                value: 1

  traefik:
    image: traefik:v2.11
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - webhost-network
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - traefik-data:/var/lib/traefik
    configs:
      - source: traefik-dynamic
        target: /etc/traefik/dynamic/dynamic.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  webhost-network:
    external: true

volumes:
  traefik-data:
    external: false

configs:
  traefik-dynamic:
    file: ./traefik/dynamic.yml
